services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: prism
      POSTGRES_PASSWORD: prism
      POSTGRES_DB: prism
    ports:
      - "5432:5432"
    volumes:
      - prism_pg:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  prism_pg:
